name: Test and Lint Python Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"] 
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        make dev
    - name: Run linting (linter, code style)
      run: make style
    - name: Run tests
      with:
        databricks-host: https://e2-demo-west.cloud.databricks.com
        databricks-token: ${{ secrets.DEPLOYMENT_TARGET_TOKEN_AWS }}
        run: make test
